//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagFlow.Web.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Langs {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MagFlow.Web.Resources.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string _14DayTrial {
            get {
                return ResourceManager.GetString("_14DayTrial", resourceCulture);
            }
        }
        
        public static string Automation {
            get {
                return ResourceManager.GetString("Automation", resourceCulture);
            }
        }
        
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        public static string EnterpriseSecurity {
            get {
                return ResourceManager.GetString("EnterpriseSecurity", resourceCulture);
            }
        }
        
        public static string LessManualWork {
            get {
                return ResourceManager.GetString("LessManualWork", resourceCulture);
            }
        }
        
        public static string LP_Section_Start_Text1 {
            get {
                return ResourceManager.GetString("LP_Section_Start_Text1", resourceCulture);
            }
        }
        
        public static string ManufacturingExcellence {
            get {
                return ResourceManager.GetString("ManufacturingExcellence", resourceCulture);
            }
        }
        
        public static string NoSetupFees {
            get {
                return ResourceManager.GetString("NoSetupFees", resourceCulture);
            }
        }
        
        public static string Optimization {
            get {
                return ResourceManager.GetString("Optimization", resourceCulture);
            }
        }
        
        public static string PlanDemo {
            get {
                return ResourceManager.GetString("PlanDemo", resourceCulture);
            }
        }
        
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        public static string RBACAccess {
            get {
                return ResourceManager.GetString("RBACAccess", resourceCulture);
            }
        }
        
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        public static string StartsHere {
            get {
                return ResourceManager.GetString("StartsHere", resourceCulture);
            }
        }
        
        public static string StreamlinedProcesses {
            get {
                return ResourceManager.GetString("StreamlinedProcesses", resourceCulture);
            }
        }
        
        public static string SystemModules {
            get {
                return ResourceManager.GetString("SystemModules", resourceCulture);
            }
        }
        
        public static string TrialPeriod {
            get {
                return ResourceManager.GetString("TrialPeriod", resourceCulture);
            }
        }
        
        public static string ModuleUsersTitle {
            get {
                return ResourceManager.GetString("ModuleUsersTitle", resourceCulture);
            }
        }
        
        public static string ModuleContractorsTitle {
            get {
                return ResourceManager.GetString("ModuleContractorsTitle", resourceCulture);
            }
        }
        
        public static string ModuleUsersDesc {
            get {
                return ResourceManager.GetString("ModuleUsersDesc", resourceCulture);
            }
        }
        
        public static string ModuleContractorsDesc {
            get {
                return ResourceManager.GetString("ModuleContractorsDesc", resourceCulture);
            }
        }
        
        public static string ModuleOrdersTitle {
            get {
                return ResourceManager.GetString("ModuleOrdersTitle", resourceCulture);
            }
        }
        
        public static string ModuleOrdersDesc {
            get {
                return ResourceManager.GetString("ModuleOrdersDesc", resourceCulture);
            }
        }
        
        public static string ModuleWaresTitle {
            get {
                return ResourceManager.GetString("ModuleWaresTitle", resourceCulture);
            }
        }
        
        public static string ModuleWaresDesc {
            get {
                return ResourceManager.GetString("ModuleWaresDesc", resourceCulture);
            }
        }
        
        public static string ModuleWarehousesTitle {
            get {
                return ResourceManager.GetString("ModuleWarehousesTitle", resourceCulture);
            }
        }
        
        public static string ModuleWarehousesDesc {
            get {
                return ResourceManager.GetString("ModuleWarehousesDesc", resourceCulture);
            }
        }
        
        public static string ModuleMachinesTitle {
            get {
                return ResourceManager.GetString("ModuleMachinesTitle", resourceCulture);
            }
        }
        
        public static string ModuleMachinesDesc {
            get {
                return ResourceManager.GetString("ModuleMachinesDesc", resourceCulture);
            }
        }
        
        public static string ModuleDocumentsTitle {
            get {
                return ResourceManager.GetString("ModuleDocumentsTitle", resourceCulture);
            }
        }
        
        public static string ModuleDocumentsDesc {
            get {
                return ResourceManager.GetString("ModuleDocumentsDesc", resourceCulture);
            }
        }
        
        public static string ModuleLogisticsTitle {
            get {
                return ResourceManager.GetString("ModuleLogisticsTitle", resourceCulture);
            }
        }
        
        public static string ModuleLogisticsDesc {
            get {
                return ResourceManager.GetString("ModuleLogisticsDesc", resourceCulture);
            }
        }
        
        public static string ModuleWorktimeTitle {
            get {
                return ResourceManager.GetString("ModuleWorktimeTitle", resourceCulture);
            }
        }
        
        public static string ModuleWorktimeDesc {
            get {
                return ResourceManager.GetString("ModuleWorktimeDesc", resourceCulture);
            }
        }
        
        public static string ModuleProdPlanTitle {
            get {
                return ResourceManager.GetString("ModuleProdPlanTitle", resourceCulture);
            }
        }
        
        public static string ModuleProdPlanDesc {
            get {
                return ResourceManager.GetString("ModuleProdPlanDesc", resourceCulture);
            }
        }
        
        public static string ModuleProcessesTitle {
            get {
                return ResourceManager.GetString("ModuleProcessesTitle", resourceCulture);
            }
        }
        
        public static string ModuleProcessesDesc {
            get {
                return ResourceManager.GetString("ModuleProcessesDesc", resourceCulture);
            }
        }
        
        public static string ModuleReportsTitle {
            get {
                return ResourceManager.GetString("ModuleReportsTitle", resourceCulture);
            }
        }
        
        public static string ModuleReportsDesc {
            get {
                return ResourceManager.GetString("ModuleReportsDesc", resourceCulture);
            }
        }
        
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        public static string CompleteManufacturingSuite {
            get {
                return ResourceManager.GetString("CompleteManufacturingSuite", resourceCulture);
            }
        }
        
        public static string LP_Section_Module_Text1 {
            get {
                return ResourceManager.GetString("LP_Section_Module_Text1", resourceCulture);
            }
        }
        
        public static string CustomPricing {
            get {
                return ResourceManager.GetString("CustomPricing", resourceCulture);
            }
        }
        
        public static string LP_Section_Pricing_Text1 {
            get {
                return ResourceManager.GetString("LP_Section_Pricing_Text1", resourceCulture);
            }
        }
        
        public static string RequestAQuote {
            get {
                return ResourceManager.GetString("RequestAQuote", resourceCulture);
            }
        }
        
        public static string EnterprisePlan {
            get {
                return ResourceManager.GetString("EnterprisePlan", resourceCulture);
            }
        }
        
        public static string EnterprisePlanDescription {
            get {
                return ResourceManager.GetString("EnterprisePlanDescription", resourceCulture);
            }
        }
        
        public static string LP_Section_Pricing_Text2 {
            get {
                return ResourceManager.GetString("LP_Section_Pricing_Text2", resourceCulture);
            }
        }
        
        public static string LP_Section_Pricing_Text3 {
            get {
                return ResourceManager.GetString("LP_Section_Pricing_Text3", resourceCulture);
            }
        }
        
        public static string LP_Section_Pricing_Text4 {
            get {
                return ResourceManager.GetString("LP_Section_Pricing_Text4", resourceCulture);
            }
        }
        
        public static string LP_Section_Pricing_Text5 {
            get {
                return ResourceManager.GetString("LP_Section_Pricing_Text5", resourceCulture);
            }
        }
        
        public static string LP_Section_Pricing_Text6 {
            get {
                return ResourceManager.GetString("LP_Section_Pricing_Text6", resourceCulture);
            }
        }
        
        public static string LP_Section_Contact_Text1 {
            get {
                return ResourceManager.GetString("LP_Section_Contact_Text1", resourceCulture);
            }
        }
        
        public static string John {
            get {
                return ResourceManager.GetString("John", resourceCulture);
            }
        }
        
        public static string Smith {
            get {
                return ResourceManager.GetString("Smith", resourceCulture);
            }
        }
        
        public static string E_mail {
            get {
                return ResourceManager.GetString("E_mail", resourceCulture);
            }
        }
        
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        public static string JohnSmithCompanyCom {
            get {
                return ResourceManager.GetString("JohnSmithCompanyCom", resourceCulture);
            }
        }
        
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        public static string YourCompanyName {
            get {
                return ResourceManager.GetString("YourCompanyName", resourceCulture);
            }
        }
        
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        public static string LP_Section_Contact_Text2 {
            get {
                return ResourceManager.GetString("LP_Section_Contact_Text2", resourceCulture);
            }
        }
        
        public static string LP_Section_Contact_Text3 {
            get {
                return ResourceManager.GetString("LP_Section_Contact_Text3", resourceCulture);
            }
        }
        
        public static string LP_Section_Contact_Text4 {
            get {
                return ResourceManager.GetString("LP_Section_Contact_Text4", resourceCulture);
            }
        }
        
        public static string LP_Section_Contact_Text5 {
            get {
                return ResourceManager.GetString("LP_Section_Contact_Text5", resourceCulture);
            }
        }
        
        public static string LP_Section_Contact_Text6 {
            get {
                return ResourceManager.GetString("LP_Section_Contact_Text6", resourceCulture);
            }
        }
        
        public static string LP_Section_Contact_Text7 {
            get {
                return ResourceManager.GetString("LP_Section_Contact_Text7", resourceCulture);
            }
        }
        
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        public static string Footer_Privacy_Text {
            get {
                return ResourceManager.GetString("Footer_Privacy_Text", resourceCulture);
            }
        }
        
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        public static string PrivacyPolicy1 {
            get {
                return ResourceManager.GetString("PrivacyPolicy1", resourceCulture);
            }
        }
        
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        public static string UnderConstruction {
            get {
                return ResourceManager.GetString("UnderConstruction", resourceCulture);
            }
        }
        
        public static string FAQ_Q1 {
            get {
                return ResourceManager.GetString("FAQ_Q1", resourceCulture);
            }
        }
        
        public static string FAQ_Q2 {
            get {
                return ResourceManager.GetString("FAQ_Q2", resourceCulture);
            }
        }
        
        public static string FAQ_Q3 {
            get {
                return ResourceManager.GetString("FAQ_Q3", resourceCulture);
            }
        }
        
        public static string FAQ_Q4 {
            get {
                return ResourceManager.GetString("FAQ_Q4", resourceCulture);
            }
        }
        
        public static string FAQ_Q5 {
            get {
                return ResourceManager.GetString("FAQ_Q5", resourceCulture);
            }
        }
        
        public static string FAQ_Q6 {
            get {
                return ResourceManager.GetString("FAQ_Q6", resourceCulture);
            }
        }
        
        public static string FAQ_A1 {
            get {
                return ResourceManager.GetString("FAQ_A1", resourceCulture);
            }
        }
        
        public static string FAQ_A2 {
            get {
                return ResourceManager.GetString("FAQ_A2", resourceCulture);
            }
        }
        
        public static string FAQ_A3 {
            get {
                return ResourceManager.GetString("FAQ_A3", resourceCulture);
            }
        }
        
        public static string FAQ_A4 {
            get {
                return ResourceManager.GetString("FAQ_A4", resourceCulture);
            }
        }
        
        public static string FAQ_A5 {
            get {
                return ResourceManager.GetString("FAQ_A5", resourceCulture);
            }
        }
        
        public static string FAQ_A6 {
            get {
                return ResourceManager.GetString("FAQ_A6", resourceCulture);
            }
        }
        
        public static string UserAlreadyLogged {
            get {
                return ResourceManager.GetString("UserAlreadyLogged", resourceCulture);
            }
        }
        
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        public static string SignIn1 {
            get {
                return ResourceManager.GetString("SignIn1", resourceCulture);
            }
        }
        
        public static string AccessYourAccount {
            get {
                return ResourceManager.GetString("AccessYourAccount", resourceCulture);
            }
        }
        
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        public static string Validation_Email {
            get {
                return ResourceManager.GetString("Validation_Email", resourceCulture);
            }
        }
        
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        public static string WeWillContactWithYou {
            get {
                return ResourceManager.GetString("WeWillContactWithYou", resourceCulture);
            }
        }
        
        public static string ResolutionNotSupported {
            get {
                return ResourceManager.GetString("ResolutionNotSupported", resourceCulture);
            }
        }
        
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        public static string StartPanel {
            get {
                return ResourceManager.GetString("StartPanel", resourceCulture);
            }
        }
        
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        public static string CouldNotLoadData {
            get {
                return ResourceManager.GetString("CouldNotLoadData", resourceCulture);
            }
        }
        
        public static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        public static string YouDontHavePermissions {
            get {
                return ResourceManager.GetString("YouDontHavePermissions", resourceCulture);
            }
        }
        
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        public static string PageDoesNotExist {
            get {
                return ResourceManager.GetString("PageDoesNotExist", resourceCulture);
            }
        }
        
        public static string CheckUrl {
            get {
                return ResourceManager.GetString("CheckUrl", resourceCulture);
            }
        }
        
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        public static string ChangeScreenToLarger {
            get {
                return ResourceManager.GetString("ChangeScreenToLarger", resourceCulture);
            }
        }
        
        public static string ForgotPasswordQuestion {
            get {
                return ResourceManager.GetString("ForgotPasswordQuestion", resourceCulture);
            }
        }
        
        public static string ForgotPasswordDescription {
            get {
                return ResourceManager.GetString("ForgotPasswordDescription", resourceCulture);
            }
        }
        
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        public static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }
        
        public static string CheckYourEmail {
            get {
                return ResourceManager.GetString("CheckYourEmail", resourceCulture);
            }
        }
        
        public static string PasswordChangeRequested {
            get {
                return ResourceManager.GetString("PasswordChangeRequested", resourceCulture);
            }
        }
        
        public static string Validation_PasswordCompare {
            get {
                return ResourceManager.GetString("Validation_PasswordCompare", resourceCulture);
            }
        }
        
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        public static string Validation_PasswordRequirements {
            get {
                return ResourceManager.GetString("Validation_PasswordRequirements", resourceCulture);
            }
        }
        
        public static string SetNewPassword {
            get {
                return ResourceManager.GetString("SetNewPassword", resourceCulture);
            }
        }
        
        public static string PasswordMinimumRequirements {
            get {
                return ResourceManager.GetString("PasswordMinimumRequirements", resourceCulture);
            }
        }
        
        public static string PasswordHasBeenChanged {
            get {
                return ResourceManager.GetString("PasswordHasBeenChanged", resourceCulture);
            }
        }
        
        public static string LoginWithNewPassword {
            get {
                return ResourceManager.GetString("LoginWithNewPassword", resourceCulture);
            }
        }
        
        public static string InvalidPasswordChange {
            get {
                return ResourceManager.GetString("InvalidPasswordChange", resourceCulture);
            }
        }
        
        public static string StartPanelWelcomeText {
            get {
                return ResourceManager.GetString("StartPanelWelcomeText", resourceCulture);
            }
        }
        
        public static string LastSessions {
            get {
                return ResourceManager.GetString("LastSessions", resourceCulture);
            }
        }
        
        public static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        public static string UsersModule {
            get {
                return ResourceManager.GetString("UsersModule", resourceCulture);
            }
        }
        
        public static string ContractorsModule {
            get {
                return ResourceManager.GetString("ContractorsModule", resourceCulture);
            }
        }
        
        public static string WaresModule {
            get {
                return ResourceManager.GetString("WaresModule", resourceCulture);
            }
        }
        
        public static string OrdersModule {
            get {
                return ResourceManager.GetString("OrdersModule", resourceCulture);
            }
        }
        
        public static string DocumentsModule {
            get {
                return ResourceManager.GetString("DocumentsModule", resourceCulture);
            }
        }
        
        public static string WarehousesModule {
            get {
                return ResourceManager.GetString("WarehousesModule", resourceCulture);
            }
        }
        
        public static string MachinesModule {
            get {
                return ResourceManager.GetString("MachinesModule", resourceCulture);
            }
        }
        
        public static string ProcessesModule {
            get {
                return ResourceManager.GetString("ProcessesModule", resourceCulture);
            }
        }
        
        public static string ReportsModule {
            get {
                return ResourceManager.GetString("ReportsModule", resourceCulture);
            }
        }
        
        public static string WorkTimeModule {
            get {
                return ResourceManager.GetString("WorkTimeModule", resourceCulture);
            }
        }
        
        public static string ProductionPlanModule {
            get {
                return ResourceManager.GetString("ProductionPlanModule", resourceCulture);
            }
        }
        
        public static string LogisticsModule {
            get {
                return ResourceManager.GetString("LogisticsModule", resourceCulture);
            }
        }
        
        public static string UsersModuleDescription {
            get {
                return ResourceManager.GetString("UsersModuleDescription", resourceCulture);
            }
        }
        
        public static string ContractorsModuleDescription {
            get {
                return ResourceManager.GetString("ContractorsModuleDescription", resourceCulture);
            }
        }
        
        public static string ProcessesModuleDescription {
            get {
                return ResourceManager.GetString("ProcessesModuleDescription", resourceCulture);
            }
        }
        
        public static string WaresModuleDescription {
            get {
                return ResourceManager.GetString("WaresModuleDescription", resourceCulture);
            }
        }
        
        public static string OrdersModuleDescription {
            get {
                return ResourceManager.GetString("OrdersModuleDescription", resourceCulture);
            }
        }
        
        public static string DocumentsModuleDescription {
            get {
                return ResourceManager.GetString("DocumentsModuleDescription", resourceCulture);
            }
        }
        
        public static string WarehousesModuleDescription {
            get {
                return ResourceManager.GetString("WarehousesModuleDescription", resourceCulture);
            }
        }
        
        public static string MachinesModuleDescription {
            get {
                return ResourceManager.GetString("MachinesModuleDescription", resourceCulture);
            }
        }
        
        public static string ReportsModuleDescription {
            get {
                return ResourceManager.GetString("ReportsModuleDescription", resourceCulture);
            }
        }
        
        public static string WorkTimeModuleDescription {
            get {
                return ResourceManager.GetString("WorkTimeModuleDescription", resourceCulture);
            }
        }
        
        public static string ProductionPlanModuleDescription {
            get {
                return ResourceManager.GetString("ProductionPlanModuleDescription", resourceCulture);
            }
        }
        
        public static string LogisticsModuleDescription {
            get {
                return ResourceManager.GetString("LogisticsModuleDescription", resourceCulture);
            }
        }
        
        public static string OpenSelected {
            get {
                return ResourceManager.GetString("OpenSelected", resourceCulture);
            }
        }
        
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        public static string NoRecentSessions {
            get {
                return ResourceManager.GetString("NoRecentSessions", resourceCulture);
            }
        }
        
        public static string ModulesOne {
            get {
                return ResourceManager.GetString("ModulesOne", resourceCulture);
            }
        }
        
        public static string ModulesFew {
            get {
                return ResourceManager.GetString("ModulesFew", resourceCulture);
            }
        }
        
        public static string ModulesMany {
            get {
                return ResourceManager.GetString("ModulesMany", resourceCulture);
            }
        }
        
        public static string TimeJustNow {
            get {
                return ResourceManager.GetString("TimeJustNow", resourceCulture);
            }
        }
        
        public static string TimeMinuteOneAgo {
            get {
                return ResourceManager.GetString("TimeMinuteOneAgo", resourceCulture);
            }
        }
        
        public static string TimeMinuteManyAgo {
            get {
                return ResourceManager.GetString("TimeMinuteManyAgo", resourceCulture);
            }
        }
        
        public static string TimeHourOneAgo {
            get {
                return ResourceManager.GetString("TimeHourOneAgo", resourceCulture);
            }
        }
        
        public static string TimeHourManyAgo {
            get {
                return ResourceManager.GetString("TimeHourManyAgo", resourceCulture);
            }
        }
        
        public static string TimeDayOneAgo {
            get {
                return ResourceManager.GetString("TimeDayOneAgo", resourceCulture);
            }
        }
        
        public static string TimeDayManyAgo {
            get {
                return ResourceManager.GetString("TimeDayManyAgo", resourceCulture);
            }
        }
        
        public static string LongTimeAgo {
            get {
                return ResourceManager.GetString("LongTimeAgo", resourceCulture);
            }
        }
        
        public static string OpenModule {
            get {
                return ResourceManager.GetString("OpenModule", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string SettingsCompany {
            get {
                return ResourceManager.GetString("SettingsCompany", resourceCulture);
            }
        }
        
        public static string AdminPanel {
            get {
                return ResourceManager.GetString("AdminPanel", resourceCulture);
            }
        }
        
        public static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        public static string Regional {
            get {
                return ResourceManager.GetString("Regional", resourceCulture);
            }
        }
        
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        public static string NameAndLastname {
            get {
                return ResourceManager.GetString("NameAndLastname", resourceCulture);
            }
        }
        
        public static string RoleSingle {
            get {
                return ResourceManager.GetString("RoleSingle", resourceCulture);
            }
        }
        
        public static string JoiningDate {
            get {
                return ResourceManager.GetString("JoiningDate", resourceCulture);
            }
        }
        
        public static string AccountStatus {
            get {
                return ResourceManager.GetString("AccountStatus", resourceCulture);
            }
        }
        
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        public static string UpdateYourAccountPassword {
            get {
                return ResourceManager.GetString("UpdateYourAccountPassword", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string Polish {
            get {
                return ResourceManager.GetString("Polish", resourceCulture);
            }
        }
        
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        public static string SystemAlerts {
            get {
                return ResourceManager.GetString("SystemAlerts", resourceCulture);
            }
        }
        
        public static string ProductionNotifications {
            get {
                return ResourceManager.GetString("ProductionNotifications", resourceCulture);
            }
        }
        
        public static string EmailNotifications {
            get {
                return ResourceManager.GetString("EmailNotifications", resourceCulture);
            }
        }
        
        public static string StartSessionFailed {
            get {
                return ResourceManager.GetString("StartSessionFailed", resourceCulture);
            }
        }
        
        public static string FailedUpdate {
            get {
                return ResourceManager.GetString("FailedUpdate", resourceCulture);
            }
        }
        
        public static string UserForeman {
            get {
                return ResourceManager.GetString("UserForeman", resourceCulture);
            }
        }
        
        public static string UserOperator {
            get {
                return ResourceManager.GetString("UserOperator", resourceCulture);
            }
        }
        
        public static string UserSupervisor {
            get {
                return ResourceManager.GetString("UserSupervisor", resourceCulture);
            }
        }
        
        public static string UserAuditor {
            get {
                return ResourceManager.GetString("UserAuditor", resourceCulture);
            }
        }
        
        public static string UserCompanyAdmin {
            get {
                return ResourceManager.GetString("UserCompanyAdmin", resourceCulture);
            }
        }
        
        public static string UserSysAdmin {
            get {
                return ResourceManager.GetString("UserSysAdmin", resourceCulture);
            }
        }
        
        public static string UserSuperAdmin {
            get {
                return ResourceManager.GetString("UserSuperAdmin", resourceCulture);
            }
        }
        
        public static string RoleForeman {
            get {
                return ResourceManager.GetString("RoleForeman", resourceCulture);
            }
        }
        
        public static string RoleOperator {
            get {
                return ResourceManager.GetString("RoleOperator", resourceCulture);
            }
        }
        
        public static string RoleSupervisor {
            get {
                return ResourceManager.GetString("RoleSupervisor", resourceCulture);
            }
        }
        
        public static string RoleAuditor {
            get {
                return ResourceManager.GetString("RoleAuditor", resourceCulture);
            }
        }
        
        public static string RoleCompanyAdmin {
            get {
                return ResourceManager.GetString("RoleCompanyAdmin", resourceCulture);
            }
        }
        
        public static string RoleSysAdmin {
            get {
                return ResourceManager.GetString("RoleSysAdmin", resourceCulture);
            }
        }
        
        public static string RoleSuperAdmin {
            get {
                return ResourceManager.GetString("RoleSuperAdmin", resourceCulture);
            }
        }
        
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        public static string DecimalSeparator {
            get {
                return ResourceManager.GetString("DecimalSeparator", resourceCulture);
            }
        }
        
        public static string DigitSeparatorCommaExample {
            get {
                return ResourceManager.GetString("DigitSeparatorCommaExample", resourceCulture);
            }
        }
        
        public static string DigitSeparatorDotExample {
            get {
                return ResourceManager.GetString("DigitSeparatorDotExample", resourceCulture);
            }
        }
        
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        public static string DateFormatExample1 {
            get {
                return ResourceManager.GetString("DateFormatExample1", resourceCulture);
            }
        }
        
        public static string DateFormatExample2 {
            get {
                return ResourceManager.GetString("DateFormatExample2", resourceCulture);
            }
        }
        
        public static string DateFormatExample3 {
            get {
                return ResourceManager.GetString("DateFormatExample3", resourceCulture);
            }
        }
        
        public static string DateFormatExample4 {
            get {
                return ResourceManager.GetString("DateFormatExample4", resourceCulture);
            }
        }
        
        public static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
        
        public static string TimeFormatExample1 {
            get {
                return ResourceManager.GetString("TimeFormatExample1", resourceCulture);
            }
        }
        
        public static string TimeFormatExample2 {
            get {
                return ResourceManager.GetString("TimeFormatExample2", resourceCulture);
            }
        }
        
        public static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        public static string TimeZoneEuropeWarsaw {
            get {
                return ResourceManager.GetString("TimeZoneEuropeWarsaw", resourceCulture);
            }
        }
        
        public static string TimeZoneUTC {
            get {
                return ResourceManager.GetString("TimeZoneUTC", resourceCulture);
            }
        }
        
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        public static string ContactDetails {
            get {
                return ResourceManager.GetString("ContactDetails", resourceCulture);
            }
        }
        
        public static string WorkingHours {
            get {
                return ResourceManager.GetString("WorkingHours", resourceCulture);
            }
        }
        
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        public static string TaxNumber {
            get {
                return ResourceManager.GetString("TaxNumber", resourceCulture);
            }
        }
        
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        public static string StreetAndNumber {
            get {
                return ResourceManager.GetString("StreetAndNumber", resourceCulture);
            }
        }
        
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
        
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        public static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        public static string LogoFormatExamples {
            get {
                return ResourceManager.GetString("LogoFormatExamples", resourceCulture);
            }
        }
        
        public static string LogoUpload {
            get {
                return ResourceManager.GetString("LogoUpload", resourceCulture);
            }
        }
        
        public static string DragFileOrUpload {
            get {
                return ResourceManager.GetString("DragFileOrUpload", resourceCulture);
            }
        }
        
        public static string DragAndDropLogo {
            get {
                return ResourceManager.GetString("DragAndDropLogo", resourceCulture);
            }
        }
        
        public static string FileTooLarge {
            get {
                return ResourceManager.GetString("FileTooLarge", resourceCulture);
            }
        }
        
        public static string FileReadError {
            get {
                return ResourceManager.GetString("FileReadError", resourceCulture);
            }
        }
        
        public static string LogoChange {
            get {
                return ResourceManager.GetString("LogoChange", resourceCulture);
            }
        }
        
        public static string LogoRemove {
            get {
                return ResourceManager.GetString("LogoRemove", resourceCulture);
            }
        }
        
        public static string RejoiningTheServer {
            get {
                return ResourceManager.GetString("RejoiningTheServer", resourceCulture);
            }
        }
        
        public static string RejoinFailedNextAttempt {
            get {
                return ResourceManager.GetString("RejoinFailedNextAttempt", resourceCulture);
            }
        }
        
        public static string RejoinFailed {
            get {
                return ResourceManager.GetString("RejoinFailed", resourceCulture);
            }
        }
        
        public static string TryAgainOrReload {
            get {
                return ResourceManager.GetString("TryAgainOrReload", resourceCulture);
            }
        }
        
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        public static string MainPhone {
            get {
                return ResourceManager.GetString("MainPhone", resourceCulture);
            }
        }
        
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        public static string ExamplePhoneNumber {
            get {
                return ResourceManager.GetString("ExamplePhoneNumber", resourceCulture);
            }
        }
        
        public static string ExampleWebsite {
            get {
                return ResourceManager.GetString("ExampleWebsite", resourceCulture);
            }
        }
        
        public static string ExampleEmail {
            get {
                return ResourceManager.GetString("ExampleEmail", resourceCulture);
            }
        }
        
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        public static string FromTime {
            get {
                return ResourceManager.GetString("FromTime", resourceCulture);
            }
        }
        
        public static string ToTime {
            get {
                return ResourceManager.GetString("ToTime", resourceCulture);
            }
        }
        
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        public static string Extend {
            get {
                return ResourceManager.GetString("Extend", resourceCulture);
            }
        }
        
        public static string AskForOffer {
            get {
                return ResourceManager.GetString("AskForOffer", resourceCulture);
            }
        }
        
        public static string Active1 {
            get {
                return ResourceManager.GetString("Active1", resourceCulture);
            }
        }
        
        public static string Expiring1 {
            get {
                return ResourceManager.GetString("Expiring1", resourceCulture);
            }
        }
        
        public static string Expiring {
            get {
                return ResourceManager.GetString("Expiring", resourceCulture);
            }
        }
        
        public static string Additional {
            get {
                return ResourceManager.GetString("Additional", resourceCulture);
            }
        }
        
        public static string Additional1 {
            get {
                return ResourceManager.GetString("Additional1", resourceCulture);
            }
        }
        
        public static string ValidUntil {
            get {
                return ResourceManager.GetString("ValidUntil", resourceCulture);
            }
        }
        
        public static string ExpiringIn {
            get {
                return ResourceManager.GetString("ExpiringIn", resourceCulture);
            }
        }
        
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        public static string ValidIndefinitely {
            get {
                return ResourceManager.GetString("ValidIndefinitely", resourceCulture);
            }
        }
        
        public static string ExtendLicense {
            get {
                return ResourceManager.GetString("ExtendLicense", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        public static string TemplateExtendLicense {
            get {
                return ResourceManager.GetString("TemplateExtendLicense", resourceCulture);
            }
        }
        
        public static string TemplateAskForModuleOffer {
            get {
                return ResourceManager.GetString("TemplateAskForModuleOffer", resourceCulture);
            }
        }
        
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        public static string MessageSent {
            get {
                return ResourceManager.GetString("MessageSent", resourceCulture);
            }
        }
        
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        public static string XOfY {
            get {
                return ResourceManager.GetString("XOfY", resourceCulture);
            }
        }
        
        public static string XToYOfZ {
            get {
                return ResourceManager.GetString("XToYOfZ", resourceCulture);
            }
        }
        
        public static string RowsPerPage {
            get {
                return ResourceManager.GetString("RowsPerPage", resourceCulture);
            }
        }
        
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        public static string AddCompany {
            get {
                return ResourceManager.GetString("AddCompany", resourceCulture);
            }
        }
        
        public static string ActiveModules {
            get {
                return ResourceManager.GetString("ActiveModules", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        public static string UserLoggedIn {
            get {
                return ResourceManager.GetString("UserLoggedIn", resourceCulture);
            }
        }
        
        public static string EventLog {
            get {
                return ResourceManager.GetString("EventLog", resourceCulture);
            }
        }
        
        public static string EventTime {
            get {
                return ResourceManager.GetString("EventTime", resourceCulture);
            }
        }
        
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        public static string DeleteUserConfirmation {
            get {
                return ResourceManager.GetString("DeleteUserConfirmation", resourceCulture);
            }
        }
        
        public static string NoModuleSelected {
            get {
                return ResourceManager.GetString("NoModuleSelected", resourceCulture);
            }
        }
        
        public static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        public static string DeleteCompanyConfirmation {
            get {
                return ResourceManager.GetString("DeleteCompanyConfirmation", resourceCulture);
            }
        }
        
        public static string ActivateModule_s {
            get {
                return ResourceManager.GetString("ActivateModule_s", resourceCulture);
            }
        }
        
        public static string CustomPeriod {
            get {
                return ResourceManager.GetString("CustomPeriod", resourceCulture);
            }
        }
        
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        public static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string LicenseExtended {
            get {
                return ResourceManager.GetString("LicenseExtended", resourceCulture);
            }
        }
        
        public static string ModulesActivated {
            get {
                return ResourceManager.GetString("ModulesActivated", resourceCulture);
            }
        }
        
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        public static string LastStep {
            get {
                return ResourceManager.GetString("LastStep", resourceCulture);
            }
        }
        
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        public static string ModulesList {
            get {
                return ResourceManager.GetString("ModulesList", resourceCulture);
            }
        }
        
        public static string ActionSucceed {
            get {
                return ResourceManager.GetString("ActionSucceed", resourceCulture);
            }
        }
        
        public static string DbName {
            get {
                return ResourceManager.GetString("DbName", resourceCulture);
            }
        }
        
        public static string SetupPassword {
            get {
                return ResourceManager.GetString("SetupPassword", resourceCulture);
            }
        }
        
        public static string PasswordHasBeenSet {
            get {
                return ResourceManager.GetString("PasswordHasBeenSet", resourceCulture);
            }
        }
        
        public static string RolesList {
            get {
                return ResourceManager.GetString("RolesList", resourceCulture);
            }
        }
        
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        public static string UsersList {
            get {
                return ResourceManager.GetString("UsersList", resourceCulture);
            }
        }
        
        public static string RolesList2 {
            get {
                return ResourceManager.GetString("RolesList2", resourceCulture);
            }
        }
        
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        public static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        public static string RolesAndAccess {
            get {
                return ResourceManager.GetString("RolesAndAccess", resourceCulture);
            }
        }
        
        public static string AccessList {
            get {
                return ResourceManager.GetString("AccessList", resourceCulture);
            }
        }
        
        public static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        public static string Adding {
            get {
                return ResourceManager.GetString("Adding", resourceCulture);
            }
        }
        
        public static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        public static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        public static string AdminAccess {
            get {
                return ResourceManager.GetString("AdminAccess", resourceCulture);
            }
        }
        
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        public static string BlockedSuccessfully {
            get {
                return ResourceManager.GetString("BlockedSuccessfully", resourceCulture);
            }
        }
        
        public static string BlockingFailed {
            get {
                return ResourceManager.GetString("BlockingFailed", resourceCulture);
            }
        }
        
        public static string UnblockedSuccessfully {
            get {
                return ResourceManager.GetString("UnblockedSuccessfully", resourceCulture);
            }
        }
        
        public static string UnblockingFailed {
            get {
                return ResourceManager.GetString("UnblockingFailed", resourceCulture);
            }
        }
        
        public static string Unblock {
            get {
                return ResourceManager.GetString("Unblock", resourceCulture);
            }
        }
        
        public static string BlockUserConfirmation {
            get {
                return ResourceManager.GetString("BlockUserConfirmation", resourceCulture);
            }
        }
        
        public static string UnblockUserConfirmation {
            get {
                return ResourceManager.GetString("UnblockUserConfirmation", resourceCulture);
            }
        }
        
        public static string DeleteUsersConfirmation {
            get {
                return ResourceManager.GetString("DeleteUsersConfirmation", resourceCulture);
            }
        }
        
        public static string BlockUsersConfirmation {
            get {
                return ResourceManager.GetString("BlockUsersConfirmation", resourceCulture);
            }
        }
        
        public static string UnblockUsersConfirmation {
            get {
                return ResourceManager.GetString("UnblockUsersConfirmation", resourceCulture);
            }
        }
        
        public static string BlockUser {
            get {
                return ResourceManager.GetString("BlockUser", resourceCulture);
            }
        }
        
        public static string UnblockUser {
            get {
                return ResourceManager.GetString("UnblockUser", resourceCulture);
            }
        }
    }
}
