//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagFlow.Web.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Langs {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MagFlow.Web.Resources.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string _14DayTrial {
            get {
                return ResourceManager.GetString("_14DayTrial", resourceCulture);
            }
        }
        
        public static string Automation {
            get {
                return ResourceManager.GetString("Automation", resourceCulture);
            }
        }
        
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        public static string EnterpriseSecurity {
            get {
                return ResourceManager.GetString("EnterpriseSecurity", resourceCulture);
            }
        }
        
        public static string LessManualWork {
            get {
                return ResourceManager.GetString("LessManualWork", resourceCulture);
            }
        }
        
        public static string LP_Section_Start_Text1 {
            get {
                return ResourceManager.GetString("LP_Section_Start_Text1", resourceCulture);
            }
        }
        
        public static string ManufacturingExcellence {
            get {
                return ResourceManager.GetString("ManufacturingExcellence", resourceCulture);
            }
        }
        
        public static string NoSetupFees {
            get {
                return ResourceManager.GetString("NoSetupFees", resourceCulture);
            }
        }
        
        public static string Optimization {
            get {
                return ResourceManager.GetString("Optimization", resourceCulture);
            }
        }
        
        public static string PlanDemo {
            get {
                return ResourceManager.GetString("PlanDemo", resourceCulture);
            }
        }
        
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        public static string RBACAccess {
            get {
                return ResourceManager.GetString("RBACAccess", resourceCulture);
            }
        }
        
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        public static string StartsHere {
            get {
                return ResourceManager.GetString("StartsHere", resourceCulture);
            }
        }
        
        public static string StreamlinedProcesses {
            get {
                return ResourceManager.GetString("StreamlinedProcesses", resourceCulture);
            }
        }
        
        public static string SystemModules {
            get {
                return ResourceManager.GetString("SystemModules", resourceCulture);
            }
        }
        
        public static string TrialPeriod {
            get {
                return ResourceManager.GetString("TrialPeriod", resourceCulture);
            }
        }
        
        public static string ModuleUsersTitle {
            get {
                return ResourceManager.GetString("ModuleUsersTitle", resourceCulture);
            }
        }
        
        public static string ModuleContractorsTitle {
            get {
                return ResourceManager.GetString("ModuleContractorsTitle", resourceCulture);
            }
        }
        
        public static string ModuleUsersDesc {
            get {
                return ResourceManager.GetString("ModuleUsersDesc", resourceCulture);
            }
        }
        
        public static string ModuleContractorsDesc {
            get {
                return ResourceManager.GetString("ModuleContractorsDesc", resourceCulture);
            }
        }
        
        public static string ModuleOrdersTitle {
            get {
                return ResourceManager.GetString("ModuleOrdersTitle", resourceCulture);
            }
        }
        
        public static string ModuleOrdersDesc {
            get {
                return ResourceManager.GetString("ModuleOrdersDesc", resourceCulture);
            }
        }
        
        public static string ModuleWaresTitle {
            get {
                return ResourceManager.GetString("ModuleWaresTitle", resourceCulture);
            }
        }
        
        public static string ModuleWaresDesc {
            get {
                return ResourceManager.GetString("ModuleWaresDesc", resourceCulture);
            }
        }
        
        public static string ModuleWarehousesTitle {
            get {
                return ResourceManager.GetString("ModuleWarehousesTitle", resourceCulture);
            }
        }
        
        public static string ModuleWarehousesDesc {
            get {
                return ResourceManager.GetString("ModuleWarehousesDesc", resourceCulture);
            }
        }
        
        public static string ModuleMachinesTitle {
            get {
                return ResourceManager.GetString("ModuleMachinesTitle", resourceCulture);
            }
        }
        
        public static string ModuleMachinesDesc {
            get {
                return ResourceManager.GetString("ModuleMachinesDesc", resourceCulture);
            }
        }
        
        public static string ModuleDocumentsTitle {
            get {
                return ResourceManager.GetString("ModuleDocumentsTitle", resourceCulture);
            }
        }
        
        public static string ModuleDocumentsDesc {
            get {
                return ResourceManager.GetString("ModuleDocumentsDesc", resourceCulture);
            }
        }
        
        public static string ModuleLogisticsTitle {
            get {
                return ResourceManager.GetString("ModuleLogisticsTitle", resourceCulture);
            }
        }
        
        public static string ModuleLogisticsDesc {
            get {
                return ResourceManager.GetString("ModuleLogisticsDesc", resourceCulture);
            }
        }
        
        public static string ModuleWorktimeTitle {
            get {
                return ResourceManager.GetString("ModuleWorktimeTitle", resourceCulture);
            }
        }
        
        public static string ModuleWorktimeDesc {
            get {
                return ResourceManager.GetString("ModuleWorktimeDesc", resourceCulture);
            }
        }
        
        public static string ModuleProdPlanTitle {
            get {
                return ResourceManager.GetString("ModuleProdPlanTitle", resourceCulture);
            }
        }
        
        public static string ModuleProdPlanDesc {
            get {
                return ResourceManager.GetString("ModuleProdPlanDesc", resourceCulture);
            }
        }
        
        public static string ModuleProcessesTitle {
            get {
                return ResourceManager.GetString("ModuleProcessesTitle", resourceCulture);
            }
        }
        
        public static string ModuleProcessesDesc {
            get {
                return ResourceManager.GetString("ModuleProcessesDesc", resourceCulture);
            }
        }
        
        public static string ModuleReportsTitle {
            get {
                return ResourceManager.GetString("ModuleReportsTitle", resourceCulture);
            }
        }
        
        public static string ModuleReportsDesc {
            get {
                return ResourceManager.GetString("ModuleReportsDesc", resourceCulture);
            }
        }
        
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        public static string CompleteManufacturingSuite {
            get {
                return ResourceManager.GetString("CompleteManufacturingSuite", resourceCulture);
            }
        }
        
        public static string LP_Section_Module_Text1 {
            get {
                return ResourceManager.GetString("LP_Section_Module_Text1", resourceCulture);
            }
        }
    }
}
