//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagFlow.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MagFlow.Web.Resources.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14-dniowy okres próbny.
        /// </summary>
        public static string _14DayTrial {
            get {
                return ResourceManager.GetString("_14DayTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odmowa dostępu.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostęp do systemu MagFlow.
        /// </summary>
        public static string AccessYourAccount {
            get {
                return ResourceManager.GetString("AccessYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatyzacja.
        /// </summary>
        public static string Automation {
            get {
                return ResourceManager.GetString("Automation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wstecz.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powrót do logowania.
        /// </summary>
        public static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień ekran na większy, żeby wyświetlić treść..
        /// </summary>
        public static string ChangeScreenToLarger {
            get {
                return ResourceManager.GetString("ChangeScreenToLarger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdź poprawność adresu albo wróć do strony głównej..
        /// </summary>
        public static string CheckUrl {
            get {
                return ResourceManager.GetString("CheckUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdź swój e-mail.
        /// </summary>
        public static string CheckYourEmail {
            get {
                return ResourceManager.GetString("CheckYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompletny Pakiet Produkcyjny.
        /// </summary>
        public static string CompleteManufacturingSuite {
            get {
                return ResourceManager.GetString("CompleteManufacturingSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź nowe hasło.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skontaktuj się.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrahenci.
        /// </summary>
        public static string ContractorsModule {
            get {
                return ResourceManager.GetString("ContractorsModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzanie danymi klientów i dostawców.
        /// </summary>
        public static string ContractorsModuleDescription {
            get {
                return ResourceManager.GetString("ContractorsModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się załadować danych, spróbuj ponownie..
        /// </summary>
        public static string CouldNotLoadData {
            get {
                return ResourceManager.GetString("CouldNotLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wycena Indywidualna.
        /// </summary>
        public static string CustomPricing {
            get {
                return ResourceManager.GetString("CustomPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumenty.
        /// </summary>
        public static string DocumentsModule {
            get {
                return ResourceManager.GetString("DocumentsModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tworzenie i przegląd dokumentów produkcyjnych i materiałowych.
        /// </summary>
        public static string DocumentsModuleDescription {
            get {
                return ResourceManager.GetString("DocumentsModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string E_mail {
            get {
                return ResourceManager.GetString("E_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Enterprise.
        /// </summary>
        public static string EnterprisePlan {
            get {
                return ResourceManager.GetString("EnterprisePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompleksowa platforma do zarządzania produkcją, magazynem i procesami operacyjnymi w jednym systemie..
        /// </summary>
        public static string EnterprisePlanDescription {
            get {
                return ResourceManager.GetString("EnterprisePlanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezpieczeństwo klasy enterprise.
        /// </summary>
        public static string EnterpriseSecurity {
            get {
                return ResourceManager.GetString("EnterpriseSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod błędu.
        /// </summary>
        public static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najczęściej zadawane pytania.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagFlow to nowoczesny system klasy MES, który wspiera zarządzanie produkcją, magazynem i procesami operacyjnymi w zakładach produkcyjnych – w czasie rzeczywistym i w jednym spójnym narzędziu..
        /// </summary>
        public static string FAQ_A1 {
            get {
                return ResourceManager.GetString("FAQ_A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System MagFlow oferowany jest w elastycznym modelu licencjonowania, dopasowanym do skali zakładu, liczby użytkowników oraz wykorzystywanych modułów. Rozliczenia prowadzone są w modelu rocznym..
        /// </summary>
        public static string FAQ_A2 {
            get {
                return ResourceManager.GetString("FAQ_A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wdrożenie odbywa się etapami – od analizy potrzeb, przez konfigurację systemu, po szkolenie użytkowników. Cały proces jest dopasowany do specyfiki zakładu i minimalizuje przestoje w pracy..
        /// </summary>
        public static string FAQ_A3 {
            get {
                return ResourceManager.GetString("FAQ_A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagFlow posiada wbudowany mechanizm ról użytkowników, które definiują dostęp do poszczególnych obszarów systemu. Każda rola określa zakres funkcjonalności i danych, do których użytkownik ma dostęp, co pozwala precyzyjnie kontrolować uprawnienia zgodnie z organizacją pracy w zakładzie..
        /// </summary>
        public static string FAQ_A4 {
            get {
                return ResourceManager.GetString("FAQ_A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak. Aktualizacje systemu MagFlow są dostępne bez dodatkowych opłat. System jest stale rozwijany, a nowe funkcjonalności powstają w oparciu o realne potrzeby użytkowników oraz doświadczenia z pracy w zakładach produkcyjnych..
        /// </summary>
        public static string FAQ_A5 {
            get {
                return ResourceManager.GetString("FAQ_A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integracje z zewnętrznymi systemami są obecnie na etapie planowania. Jesteśmy otwarci na rozmowy dotyczące integracji z systemami ERP oraz innymi rozwiązaniami wykorzystywanymi w zakładach produkcyjnych i sukcesywnie będziemy rozwijać ten obszar wraz z potrzebami klientów..
        /// </summary>
        public static string FAQ_A6 {
            get {
                return ResourceManager.GetString("FAQ_A6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czym jest MagFlow?.
        /// </summary>
        public static string FAQ_Q1 {
            get {
                return ResourceManager.GetString("FAQ_Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jak wygląda model licencjonowania systemu MagFlow?.
        /// </summary>
        public static string FAQ_Q2 {
            get {
                return ResourceManager.GetString("FAQ_Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jak przebiega proces wdrożenia systemu?.
        /// </summary>
        public static string FAQ_Q3 {
            get {
                return ResourceManager.GetString("FAQ_Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy MagFlow pozwala zarządzać uprawnieniami użytkowników?.
        /// </summary>
        public static string FAQ_Q4 {
            get {
                return ResourceManager.GetString("FAQ_Q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy system jest regularnie aktualizowany?.
        /// </summary>
        public static string FAQ_Q5 {
            get {
                return ResourceManager.GetString("FAQ_Q5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy system MagFlow umożliwia integrację z innymi systemami?.
        /// </summary>
        public static string FAQ_Q6 {
            get {
                return ResourceManager.GetString("FAQ_Q6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korzystanie z tej strony oznacza akceptację.
        /// </summary>
        public static string Footer_Privacy_Text {
            get {
                return ResourceManager.GetString("Footer_Privacy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapomniałem hasła.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj e-mail powiązany z kontem, aby zresetować hasło.
        /// </summary>
        public static string ForgotPasswordDescription {
            get {
                return ResourceManager.GetString("ForgotPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapomniałeś hasła?.
        /// </summary>
        public static string ForgotPasswordQuestion {
            get {
                return ResourceManager.GetString("ForgotPasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powrót.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowy adres e-mail lub hasło..
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się zmienić hasła. Spróbuj później.
        /// </summary>
        public static string InvalidPasswordChange {
            get {
                return ResourceManager.GetString("InvalidPasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        public static string John {
            get {
                return ResourceManager.GetString("John", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jan.kowalski@firma.com.
        /// </summary>
        public static string JohnSmithCompanyCom {
            get {
                return ResourceManager.GetString("JohnSmithCompanyCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatnie sesje.
        /// </summary>
        public static string LastSessions {
            get {
                return ResourceManager.GetString("LastSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mniej pracy ręcznej.
        /// </summary>
        public static string LessManualWork {
            get {
                return ResourceManager.GetString("LessManualWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się zalogować do systemu. Spróbuj ponownie..
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Możesz teraz zalogować się przy użyciu nowego hasła.
        /// </summary>
        public static string LoginWithNewPassword {
            get {
                return ResourceManager.GetString("LoginWithNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistyka.
        /// </summary>
        public static string LogisticsModule {
            get {
                return ResourceManager.GetString("LogisticsModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koordynacja transportu, dostaw oraz przepływu materiałów między magazynami.
        /// </summary>
        public static string LogisticsModuleDescription {
            get {
                return ResourceManager.GetString("LogisticsModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj się.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porozmawiaj o swojej produkcji.
        /// </summary>
        public static string LP_Section_Contact_Text1 {
            get {
                return ResourceManager.GetString("LP_Section_Contact_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indywidualna Wycena i Moduły.
        /// </summary>
        public static string LP_Section_Contact_Text2 {
            get {
                return ResourceManager.GetString("LP_Section_Contact_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omów wycenę dopasowaną do skali działalności oraz planowanego sposobu korzystania z platformy..
        /// </summary>
        public static string LP_Section_Contact_Text3 {
            get {
                return ResourceManager.GetString("LP_Section_Contact_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategia Wdrożenia.
        /// </summary>
        public static string LP_Section_Contact_Text4 {
            get {
                return ResourceManager.GetString("LP_Section_Contact_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznaj możliwe warianty uruchomienia systemu oraz orientacyjny harmonogram startu..
        /// </summary>
        public static string LP_Section_Contact_Text5 {
            get {
                return ResourceManager.GetString("LP_Section_Contact_Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspekty Techniczne.
        /// </summary>
        public static string LP_Section_Contact_Text6 {
            get {
                return ResourceManager.GetString("LP_Section_Contact_Text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omów podstawowe kwestie techniczne związane z działaniem i konfiguracją systemu..
        /// </summary>
        public static string LP_Section_Contact_Text7 {
            get {
                return ResourceManager.GetString("LP_Section_Contact_Text7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elastyczne, w pełni zintegrowane moduły, które współpracują ze sobą, aby usprawnić przepływy pracy, zwiększyć efektywność i zapewnić pełną kontrolę nad całym procesem produkcyjnym..
        /// </summary>
        public static string LP_Section_Module_Text1 {
            get {
                return ResourceManager.GetString("LP_Section_Module_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skalowalne rozwiązanie zaprojektowane z myślą o rzeczywistych warunkach produkcyjnych..
        /// </summary>
        public static string LP_Section_Pricing_Text1 {
            get {
                return ResourceManager.GetString("LP_Section_Pricing_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakres funkcjonalny dopasowany do potrzeb firmy.
        /// </summary>
        public static string LP_Section_Pricing_Text2 {
            get {
                return ResourceManager.GetString("LP_Section_Pricing_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modułowa struktura umożliwiająca stopniową rozbudowę.
        /// </summary>
        public static string LP_Section_Pricing_Text3 {
            get {
                return ResourceManager.GetString("LP_Section_Pricing_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wsparcie przy wdrożeniu i pierwszym uruchomieniu.
        /// </summary>
        public static string LP_Section_Pricing_Text4 {
            get {
                return ResourceManager.GetString("LP_Section_Pricing_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomoc techniczna w trakcie użytkowania systemu.
        /// </summary>
        public static string LP_Section_Pricing_Text5 {
            get {
                return ResourceManager.GetString("LP_Section_Pricing_Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elastyczne warunki współpracy wraz z rozwojem firmy.
        /// </summary>
        public static string LP_Section_Pricing_Text6 {
            get {
                return ResourceManager.GetString("LP_Section_Pricing_Text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowoczesny MES zaprojektowany dla firm, które chcą usprawnić operacje, uporządkować procesy i wyeliminować codzienny chaos produkcyjny. Zapewnia większą przejrzystość działań, ułatwia koordynację zespołów i wspiera sprawniejsze zarządzanie całą produkcją — od planowania po realizację..
        /// </summary>
        public static string LP_Section_Start_Text1 {
            get {
                return ResourceManager.GetString("LP_Section_Start_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maszyny.
        /// </summary>
        public static string MachinesModule {
            get {
                return ResourceManager.GetString("MachinesModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitorowanie pracy maszyn i ich efektywności.
        /// </summary>
        public static string MachinesModuleDescription {
            get {
                return ResourceManager.GetString("MachinesModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona główna.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doskonałość w produkcji.
        /// </summary>
        public static string ManufacturingExcellence {
            get {
                return ResourceManager.GetString("ManufacturingExcellence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzaj pełną bazą klientów i dostawców, aby szybciej obsługiwać transakcje i budować trwałe relacje biznesowe..
        /// </summary>
        public static string ModuleContractorsDesc {
            get {
                return ResourceManager.GetString("ModuleContractorsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrahenci.
        /// </summary>
        public static string ModuleContractorsTitle {
            get {
                return ResourceManager.GetString("ModuleContractorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatyzuj obieg wszystkich dokumentów magazynowych i sprzedażowych, minimalizując błędy i zyskując pełną kontrolę nad przepływem towarów..
        /// </summary>
        public static string ModuleDocumentsDesc {
            get {
                return ResourceManager.GetString("ModuleDocumentsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumenty.
        /// </summary>
        public static string ModuleDocumentsTitle {
            get {
                return ResourceManager.GetString("ModuleDocumentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planuj i koordynuj transporty, wysyłki i odbiory, aby logistyka Twojej firmy była szybka, przewidywalna i dobrze zorganizowana..
        /// </summary>
        public static string ModuleLogisticsDesc {
            get {
                return ResourceManager.GetString("ModuleLogisticsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistyka.
        /// </summary>
        public static string ModuleLogisticsTitle {
            get {
                return ResourceManager.GetString("ModuleLogisticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzaj parkiem maszynowym, ich obciążeniem i statusami, aby utrzymać wysoką dostępność i minimalizować ryzyko przestojów..
        /// </summary>
        public static string ModuleMachinesDesc {
            get {
                return ResourceManager.GetString("ModuleMachinesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maszyny.
        /// </summary>
        public static string ModuleMachinesTitle {
            get {
                return ResourceManager.GetString("ModuleMachinesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usprawnij cały proces obsługi klienta i dostawców dzięki szybkiemu tworzeniu, śledzeniu i realizacji zamówień w jednym miejscu..
        /// </summary>
        public static string ModuleOrdersDesc {
            get {
                return ResourceManager.GetString("ModuleOrdersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamówienia.
        /// </summary>
        public static string ModuleOrdersTitle {
            get {
                return ResourceManager.GetString("ModuleOrdersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modeluj, standaryzuj i kontroluj każdy etap produkcji, aby zwiększyć powtarzalność i jakość wytwarzania..
        /// </summary>
        public static string ModuleProcessesDesc {
            get {
                return ResourceManager.GetString("ModuleProcessesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesy Produkcyjne.
        /// </summary>
        public static string ModuleProcessesTitle {
            get {
                return ResourceManager.GetString("ModuleProcessesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buduj efektywne harmonogramy oraz optymalizuj wykorzystanie maszyn, ludzi i materiałów, aby zlecenia były realizowane na czas..
        /// </summary>
        public static string ModuleProdPlanDesc {
            get {
                return ResourceManager.GetString("ModuleProdPlanDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Produkcji.
        /// </summary>
        public static string ModuleProdPlanTitle {
            get {
                return ResourceManager.GetString("ModuleProdPlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otrzymuj przejrzyste raporty i kluczowe wskaźniki, które pomagają podejmować lepsze decyzje operacyjne i strategiczne..
        /// </summary>
        public static string ModuleReportsDesc {
            get {
                return ResourceManager.GetString("ModuleReportsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporty.
        /// </summary>
        public static string ModuleReportsTitle {
            get {
                return ResourceManager.GetString("ModuleReportsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moduły.
        /// </summary>
        public static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontroluj dostęp do funkcji systemu i dostosowuj uprawnienia do struktury Twojej firmy, zapewniając bezpieczeństwo i porządek..
        /// </summary>
        public static string ModuleUsersDesc {
            get {
                return ResourceManager.GetString("ModuleUsersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownicy.
        /// </summary>
        public static string ModuleUsersTitle {
            get {
                return ResourceManager.GetString("ModuleUsersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoruj stany, ruchy i rezerwacje materiałowe w czasie rzeczywistym, aby magazyn zawsze działał płynnie i bez przestojów..
        /// </summary>
        public static string ModuleWarehousesDesc {
            get {
                return ResourceManager.GetString("ModuleWarehousesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazyn.
        /// </summary>
        public static string ModuleWarehousesTitle {
            get {
                return ResourceManager.GetString("ModuleWarehousesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twórz kompletne kartoteki produktów z własnymi parametrami i historią, dzięki czemu zawsze wiesz, czym dysponuje Twoja firma..
        /// </summary>
        public static string ModuleWaresDesc {
            get {
                return ResourceManager.GetString("ModuleWaresDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Towary.
        /// </summary>
        public static string ModuleWaresTitle {
            get {
                return ResourceManager.GetString("ModuleWaresTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestruj czas i aktywność pracowników na zmianach oraz zleceniach, aby zyskać pełną przejrzystość nad realizacją pracy w firmie..
        /// </summary>
        public static string ModuleWorktimeDesc {
            get {
                return ResourceManager.GetString("ModuleWorktimeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ewidencja Pracy.
        /// </summary>
        public static string ModuleWorktimeTitle {
            get {
                return ResourceManager.GetString("ModuleWorktimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowe hasło.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak opłat wdrożeniowych.
        /// </summary>
        public static string NoSetupFees {
            get {
                return ResourceManager.GetString("NoSetupFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz wybrane.
        /// </summary>
        public static string OpenSelected {
            get {
                return ResourceManager.GetString("OpenSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optymalizacja.
        /// </summary>
        public static string Optimization {
            get {
                return ResourceManager.GetString("Optimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamówienia.
        /// </summary>
        public static string OrdersModule {
            get {
                return ResourceManager.GetString("OrdersModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsługa, śledzenie i realizacja zamówień produkcyjnych.
        /// </summary>
        public static string OrdersModuleDescription {
            get {
                return ResourceManager.GetString("OrdersModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona, której szukasz, nie istnieje lub została przeniesiona..
        /// </summary>
        public static string PageDoesNotExist {
            get {
                return ResourceManager.GetString("PageDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie odnaleziono strony.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link do zmiany hasła został wysłany. Jeśli nie widzisz wiadomości e-mail, sprawdź spam albo skontaktuj się poprzez adres:.
        /// </summary>
        public static string PasswordChangeRequested {
            get {
                return ResourceManager.GetString("PasswordChangeRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło zostało zmienione.
        /// </summary>
        public static string PasswordHasBeenChanged {
            get {
                return ResourceManager.GetString("PasswordHasBeenChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 8 znaków, mała litera, wielka litera i cyfra.
        /// </summary>
        public static string PasswordMinimumRequirements {
            get {
                return ResourceManager.GetString("PasswordMinimumRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaplanuj demo.
        /// </summary>
        public static string PlanDemo {
            get {
                return ResourceManager.GetString("PlanDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta Cenowa.
        /// </summary>
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polityka Prywatności.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polityki Prywatności.
        /// </summary>
        public static string PrivacyPolicy1 {
            get {
                return ResourceManager.GetString("PrivacyPolicy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesy.
        /// </summary>
        public static string ProcessesModule {
            get {
                return ResourceManager.GetString("ProcessesModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzanie i monitorowanie przebiegu produkcji w czasie rzeczywistym.
        /// </summary>
        public static string ProcessesModuleDescription {
            get {
                return ResourceManager.GetString("ProcessesModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan produkcji.
        /// </summary>
        public static string ProductionPlanModule {
            get {
                return ResourceManager.GetString("ProductionPlanModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tworzenie harmonogramów produkcyjnych i monitorowanie realizacji zleceń.
        /// </summary>
        public static string ProductionPlanModuleDescription {
            get {
                return ResourceManager.GetString("ProductionPlanModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostęp RBAC.
        /// </summary>
        public static string RBACAccess {
            get {
                return ResourceManager.GetString("RBACAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamiętaj mnie.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporty.
        /// </summary>
        public static string ReportsModule {
            get {
                return ResourceManager.GetString("ReportsModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analiza danych produkcyjnych i generowanie raportów.
        /// </summary>
        public static string ReportsModuleDescription {
            get {
                return ResourceManager.GetString("ReportsModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamów wycenę.
        /// </summary>
        public static string RequestAQuote {
            get {
                return ResourceManager.GetString("RequestAQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymagane.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zresetuj hasło.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozdzielczość nieobsługiwana.
        /// </summary>
        public static string ResolutionNotSupported {
            get {
                return ResourceManager.GetString("ResolutionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przywróć.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezpieczeństwo.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaznacz wszystko.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustaw nowe hasło.
        /// </summary>
        public static string SetNewPassword {
            get {
                return ResourceManager.GetString("SetNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się.
        /// </summary>
        public static string SignIn1 {
            get {
                return ResourceManager.GetString("SignIn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kowalski.
        /// </summary>
        public static string Smith {
            get {
                return ResourceManager.GetString("Smith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coś poszło nie tak.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel startowy.
        /// </summary>
        public static string StartPanel {
            get {
                return ResourceManager.GetString("StartPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj ponownie! Wybierz moduły, aby uzyskać dostęp do narzędzi produkcyjnych..
        /// </summary>
        public static string StartPanelWelcomeText {
            get {
                return ResourceManager.GetString("StartPanelWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zaczyna się tutaj.
        /// </summary>
        public static string StartsHere {
            get {
                return ResourceManager.GetString("StartsHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawniejsze procesy.
        /// </summary>
        public static string StreamlinedProcesses {
            get {
                return ResourceManager.GetString("StreamlinedProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moduły Systemu.
        /// </summary>
        public static string SystemModules {
            get {
                return ResourceManager.GetString("SystemModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okres próbny.
        /// </summary>
        public static string TrialPeriod {
            get {
                return ResourceManager.GetString("TrialPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spróbuj ponownie.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W trakcie budowy.
        /// </summary>
        public static string UnderConstruction {
            get {
                return ResourceManager.GetString("UnderConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik jest już zalogowany.
        /// </summary>
        public static string UserAlreadyLogged {
            get {
                return ResourceManager.GetString("UserAlreadyLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownicy.
        /// </summary>
        public static string UsersModule {
            get {
                return ResourceManager.GetString("UsersModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzanie kontami, rolami 
        ///i uprawnieniami użytkowników.
        /// </summary>
        public static string UsersModuleDescription {
            get {
                return ResourceManager.GetString("UsersModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj poprawny adres e-mail..
        /// </summary>
        public static string Validation_Email {
            get {
                return ResourceManager.GetString("Validation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oba hasła muszą być identyczne.
        /// </summary>
        public static string Validation_PasswordCompare {
            get {
                return ResourceManager.GetString("Validation_PasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło nie spełnia wymagań.
        /// </summary>
        public static string Validation_PasswordRequirements {
            get {
                return ResourceManager.GetString("Validation_PasswordRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole jest wymagane..
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazyny.
        /// </summary>
        public static string WarehousesModule {
            get {
                return ResourceManager.GetString("WarehousesModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrola stanów magazynowych oraz przepływu materiałów.
        /// </summary>
        public static string WarehousesModuleDescription {
            get {
                return ResourceManager.GetString("WarehousesModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Towary.
        /// </summary>
        public static string WaresModule {
            get {
                return ResourceManager.GetString("WaresModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tworzenie, edycja i katalogowanie towarów wraz z ich właściwościami.
        /// </summary>
        public static string WaresModuleDescription {
            get {
                return ResourceManager.GetString("WaresModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skontaktujemy się z Tobą!.
        /// </summary>
        public static string WeWillContactWithYou {
            get {
                return ResourceManager.GetString("WeWillContactWithYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas pracy.
        /// </summary>
        public static string WorkTimeModule {
            get {
                return ResourceManager.GetString("WorkTimeModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja i analiza czasu pracy pracowników.
        /// </summary>
        public static string WorkTimeModuleDescription {
            get {
                return ResourceManager.GetString("WorkTimeModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie masz uprawnień dostępu do tej strony..
        /// </summary>
        public static string YouDontHavePermissions {
            get {
                return ResourceManager.GetString("YouDontHavePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa Twojej firmy.
        /// </summary>
        public static string YourCompanyName {
            get {
                return ResourceManager.GetString("YourCompanyName", resourceCulture);
            }
        }
    }
}
